version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: diagnosis_helper
      POSTGRES_USER: diagnosis_user
      POSTGRES_PASSWORD: password
    ports:
      - "3031:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
